package InterFaceGrafica;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author STEVAOSEVERORODRIGUE
 */
public class MinhaInterface extends javax.swing.JFrame {

    /**
     * Creates new form MinhaInterface
     */
    public MinhaInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Painel = new javax.swing.JPanel();
        Texto1 = new javax.swing.JLabel();
        Botao1 = new javax.swing.JButton();
        campoTexto = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Painel.setBackground(new java.awt.Color(0, 0, 204));
        Painel.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        Painel.setForeground(new java.awt.Color(204, 204, 204));

        Texto1.setBackground(new java.awt.Color(255, 255, 255));
        Texto1.setFont(new java.awt.Font("Sitka Heading", 3, 24)); // NOI18N
        Texto1.setForeground(new java.awt.Color(0, 0, 0));
        Texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto1.setText("GRÊMIO FUTEBOL CLUBE");

        Botao1.setBackground(new java.awt.Color(0, 0, 51));
        Botao1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Botao1.setForeground(new java.awt.Color(255, 255, 255));
        Botao1.setText("Você é Tricolor ? ");
        Botao1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Botao1AncestorAdded(evt);
                evento1(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao1ActionPerformed(evt);
            }
        });

        campoTexto.setBackground(new java.awt.Color(255, 255, 255));
        campoTexto.setForeground(new java.awt.Color(0, 0, 0));
        campoTexto.setText("Escreva algo...");
        campoTexto.setToolTipText("");
        campoTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTextoFocusLost(evt);
            }
        });
        campoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGroup(PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(Botao1))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(627, Short.MAX_VALUE))
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao1ActionPerformed
        // TODO add your handling code here:
        //System.out.println(" VAMOO GRÊMIOO !!!!!!!!!");
        Texto1.setText("INTER FUTEBOL CLUBE");
         Painel.setBackground(new java.awt.Color(204, 0, 0)); //[204,0,0]
          Botao1.setBackground(new java.awt.Color(255, 255, 255));
        Botao1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Botao1.setForeground(new java.awt.Color(204, 0, 0));
        Botao1.setText(" È O INTER !!! ");
        /*if(NameGremio.getText() == "GRÊMIO FUTEBOL CLUBE"){
            NameGremio.setText("Vamo Tevinho ");
        } else {
            NameGremio.setText("GRÊMIO FUTEBOL CLUBE");
        }
    }//GEN-LAST:event_Botao1ActionPerformed
*/
    }
    private void Botao1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Botao1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Botao1AncestorAdded

    private void evento1(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_evento1
        // TODO add your handling code here:
    }//GEN-LAST:event_evento1

    private void campoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoActionPerformed

    private void campoTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTextoFocusGained
if("Escreva algo... ".equals(campoTexto.getText())){
    campoTexto.setText("");
}
    }//GEN-LAST:event_campoTextoFocusGained

    private void campoTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTextoFocusLost
        if("".equals(campoTexto.getText())){
            campoTexto.setText("Escreva algo...");
        }
    }//GEN-LAST:event_campoTextoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhaInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao1;
    private javax.swing.JPanel Painel;
    private javax.swing.JLabel Texto1;
    private javax.swing.JTextField campoTexto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
