/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Bag;;

public class App {
    public static void main(String[] args) {
        new view(); // Inicia a tela de Viagem
    }
}

