/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AULA02;

public class App {


    public static void main(String[] args) {
        
        //Pessoas pessoa1 = new Pessoas("Stevao", 18); 
        //pessoa1.apresentar();
        
        Carro carro1 = new Carro("Nivus","Azul","HA22GHA",1000, true );
        carro1.Garagem();
        System.out.println("==============================================");
        carro1.novoOUnao();
        
        //Animal bixo1 = new Animal("Max", "Labrador", "Cachorro");
        //bixo1.Zoologico();
        
        //double numero1 = 50;
        //double numero2 = 50;
        
        //Operadores Aritmeticos
        /*
       double soma = numero1 + numero2;
       double sub = numero1 -  numero2;
       double mult = numero1 * numero2;
       double div = numero1 / numero2;
       double modulo = numero1 % numero2;
       
       System.out.println(soma);
       System.out.println(sub);
       System.out.println(mult);
       System.out.println(div);
       System.out.println(modulo); 
       */
        /*
        
        //Comparadores 
       System.out.println(numero1 == numero2); 
        System.out.println(numero1 != numero2);
        System.out.println(numero1 > numero2);
        System.out.println(numero1 < numero2);
        System.out.println(numero1 <= numero2);      
        System.out.println(numero1 >= numero2);
        */
        /*
        boolean ligada = true;
        boolean quebrado = false;
        
        System.out.println(ligada && quebrado);
        System.out.println(ligada || quebrado);
        System.out.println(ligada && ! quebrado);
        
        // If e else 
        int idade = 18;
        boolean maiorIdade = idade >= 18;
        boolean temCarteira = false;
        
        if (maiorIdade && temCarteira) {
            System.out.println("Voce pode dirigir!!!");
        } 
        else if ( maiorIdade){
            System.out.println("Voce e de maior mais nao tem carteira");
        } else {
            System.out.println("Voce e de menor, volte a estudar!!!");
        }

        String Time = "Inter";
        
        switch(Time) {
            case "Grêmio":
        System.out.println("Melhor do sul");
        break;
            case "Inter":
                System.out.println("Pau no cu do inter!!!!!!!!");
                break;
            default:
                System.out.println("Nao conheco esse time");
                break;
        }
        
        //Loops
        int voltas = 0;
        while(voltas <= 10) {
            System.out.println("Voce ja pedalou" + voltas + "voltas!");
            voltas++;
        }
        
        for(int contagem = 0; contagem <= 10; contagem ++){
            System.out.println(contagem);
        }
*/
    }
}
        
 
