/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LOGIN_SQLITE;

import java.sql.Connection;

public class App {
            public static void main(String[] args) {
        LoginSQLITE LOGIN_SQLITE = new LoginSQLITE(); 
        Connection conexao = LOGIN_SQLITE.conectar();
        
        CriarTabela.criarTabelaUsuarios(conexao);
        
          InserirUsuario.inserirUsuario(conexao, "Stevão","9953");
          InserirUsuario.inserirUsuario(conexao, "Boladin","0000"); 
          InserirUsuario.inserirUsuario(conexao, "Teteu","1234");
            
            }
}
